name = "portfolio"
compatibility_date = "2026-03-02"
workers_dev = true
preview_urls = true

[assets]
directory = "./dist"
not_found_handling = "404-page"

[[routes]]
pattern = "felix-hoffmann.dev"
zone_name = "felix-hoffmann.dev"
custom_domain = true
