name: 🐛 Bug Report
title: "🐛[bug] "
description: Report a bug
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear description of what the bug is. Please attach screenshot into Screenshot section below.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the bug
      placeholder: |
        1. Visit page ...
        2. Click on ...
        3. Errors show up ...
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: It should work like ...
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: If applicable, add screenshots to help explain your problem.
      placeholder: It should work like ...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information
      value: |
        - OS: [e.g. Windows, Linux]
        - Python: [e.g. 3.8, 3.9, 3.10]
        - Poetry: [e.g. 1.2]
      placeholder: It should work like ...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
