name: Gatsby Publish

on:
  push:
    branches: [main]

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOY_PERSONAL_SITE }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
